### ISSUE TITLE
Issue with the initial connectivity

### ISSUE THREAD

**Issue by FaridTavakol** [ProstateBRP/BRPRobot2021#8]
The initial connection between the robot and the navigation software does not connect and requires disconnection of the navigation software and reconnecting it. 
Based on my investigation on the issue, if you follow the step of 1) running the robot software, 2) running the slicer module and opening a server port, and finally 3) connecting the navigation software to both, upon clicking on start up button, nothing happens and the message does not properly sent to the robot. However, if the navigation software is closed and opened again, upon clicking on the startup button, the message properly is sent to the robot and a confirmation and current robot status is sent back to the navigation software. However, this time the startup button does not get updated and still the rest of the buttons are grayed out.
The issue **sometimes** seems to go away when the slicer module disconnects and another port is used.

**Comment by FaridTavakol** [comment]
Upon further investigation, one issue might be that the Slicer module does not recognize the change from Start UP phase to Start Up phase. This results in an error shown in the Slicer terminal when the Application is running. This requires the user to close Slicer and reopen it in order to make the issue go away.

**Comment by rebeccalisk** [comment]
Hey Farid -- What do you mean by the Start UP vs. Start Up phases? My understanding is that there should be only one phase, START_UP. I haven't gotten any errors in the Slicer terminal, would you be able to send me a screenshot of what you see?

**Comment by FaridTavakol** [comment]
> 
![Screenshot from 2022-01-19 15-11-55](https://user-images.githubusercontent.com/54147195/150206638-a2b2675f-8a2b-453e-85d1-538e4b4a3079.png)

**Comment by FaridTavakol** [comment]
In the above screen shot, the Slicer module was first opened on port 18944. Then due to not being able to send the Start-up message to the robot, the port was closed and another port 18945 was opened. This time upon clicking on the Start-up, the error shown in the bottom of the above image was seen in the python console. This is probably the fact that Slicer was keeping the state in its memory and upon multiple clicking on the same button it throws an error which should be addressed in this instance.

**Comment by rebeccalisk** [comment]
Ohhh. Thank you! Something is up with the timestamp in the acknowledgement it seems, which is preventing the command and acknowledgement from matching up. I’m at a doctors appt right now but I should be able to fix that easily soon!

**Comment by rebeccalisk** [comment]
I’m not exactly sure why it’s different upon successive start ups, but I’ll investigate. Thanks so much
